---
title: Kim Clements
email: your-email@example.com
description: Illustrator in London. Owns lots of jumpers
baseurl: ''
url: ''
twitter_username: jekyllrb
github_username: jekyll
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
- jekyll-menus
timezone: Etc/UTC
